# Generated by Django 4.1.2 on 2023-04-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_category_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=15),
        ),
    ]
