# Generated by Django 4.1.2 on 2023-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyalti',
            options={'verbose_name': 'LOYALTY SUMMARY', 'verbose_name_plural': 'LOYALTY SUMMARY'},
        ),
        migrations.AlterModelOptions(
            name='loyaltientity',
            options={'verbose_name': 'LOYALTY CLAUSE', 'verbose_name_plural': 'LOYALTY CLAUSE'},
        ),
        migrations.AlterModelOptions(
            name='loyaltitransaction',
            options={'verbose_name': 'LOYALTY TRANSACTIONS', 'verbose_name_plural': 'LOYALTY TRANSACTIONS'},
        ),
        migrations.AddField(
            model_name='loyaltientity',
            name='proints_upgrade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
