# Generated by Django 4.1.2 on 2023-03-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0004_rename_cust_id_paymentrequest_channel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='register_no',
            new_name='billNumberOrInvoiceNumber',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='register_no_or_cust_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='transactionReferenceNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
