# Generated by Django 4.1.2 on 2023-03-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0005_rename_register_no_paymentrequest_billnumberorinvoicenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='crmId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
