# Generated by Django 4.1.2 on 2023-04-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0006_paymentrequest_crmid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirylog',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_log', to='profileutility.profile'),
        ),
        migrations.AlterField(
            model_name='enquirylog',
            name='profile_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_address', to='profileutility.profileaddress'),
        ),
    ]
