# Generated by Django 4.1.2 on 2023-04-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0007_alter_enquirylog_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Expired', 'Expired'), ('Declined', 'Declined')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Expired', 'Expired')], default='Pending', max_length=50),
        ),
    ]
