# Generated by Django 4.1.2 on 2023-05-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0008_alter_paymentrequest_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
