# Generated by Django 4.1.2 on 2023-05-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0009_paymentrequest_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProfileVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(blank=True, max_length=255, null=True)),
                ('name_as_per_pan', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_image', models.ImageField(upload_to='store/images')),
                ('verified_pan', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pan_profile', to='profileutility.profile')),
            ],
            options={
                'verbose_name': 'Profile Documents',
                'verbose_name_plural': 'Profile Documents',
            },
        ),
    ]
