# Generated by Django 4.1.2 on 2023-05-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0010_profile_verified_profile_profileverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileverification',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profileverification',
            name='name_as_per_pan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
