# Generated by Django 4.1.2 on 2023-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.CharField(blank=True, max_length=255, null=True)),
                ('is_popular', models.CharField(blank=True, max_length=255, null=True)),
                ('rto_code', models.CharField(blank=True, max_length=255, null=True)),
                ('rto_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rto_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
