# Generated by Django 4.1.2 on 2023-05-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilsplayground', '0003_alter_city_options_alter_outlet_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(blank=True, max_length=250, null=True)),
                ('version_description', models.CharField(blank=True, max_length=250, null=True)),
                ('version_number', models.CharField(blank=True, max_length=250, null=True)),
                ('version_notes', models.CharField(blank=True, max_length=250, null=True)),
                ('version_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('version_status', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
            },
        ),
    ]
