# Generated by Django 4.1.2 on 2023-04-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='varient',
            new_name='addons',
        ),
        migrations.AddField(
            model_name='insurance',
            name='registered_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='variant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usedcarbooking',
            name='scheduled',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
