# Generated by Django 4.1.2 on 2023-04-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_varient_insurance_addons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcarbooking',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usedcarbooking',
            name='kms_driven_ending',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usedcarbooking',
            name='kms_driven_starting',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usedcarbooking',
            name='year',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
