# Generated by Django 4.1.2 on 2023-04-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_usedcarbooking_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbooking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
