# Generated by Django 4.1.2 on 2023-05-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_appbooking_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='usedcarbooking',
            name='price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
