# Generated by Django 4.1.2 on 2023-05-18 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0012_profile_app_version'),
        ('bookings', '0005_accessory_quantity_alter_usedcarbooking_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyalti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_points', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_updated_points', models.DateTimeField(auto_now=True)),
                ('business_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profileutility.profile')),
            ],
            options={
                'verbose_name': 'Loyalti',
                'verbose_name_plural': 'Loyalties',
            },
        ),
    ]
