# Generated by Django 4.1.2 on 2023-05-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileutility', '0012_profile_app_version'),
        ('bookings', '0006_loyalti'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='cust_id_or_reg_no',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appbooking',
            name='cust_id_or_reg_no',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newcarbooking',
            name='cust_id_or_reg_no',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cust_id_or_reg_no',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usedcarbooking',
            name='cust_id_or_reg_no',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='LoyaltiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=50)),
                ('time_of_transaction', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('Add', 'Add'), ('Redeem', 'Redeem')], default='Add', max_length=50)),
                ('loyalti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.loyalti')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profileutility.profile')),
            ],
            options={
                'verbose_name': 'Loyalti Transaction',
                'verbose_name_plural': 'Loyalti Transaction',
            },
        ),
    ]
