# Generated by Django 4.1.2 on 2023-05-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_loyaltientity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltitransaction',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='loyaltitransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Add', 'Add'), ('Redeem', 'Redeem')], default=None, max_length=50),
        ),
    ]
