# Generated by Django 4.1.2 on 2023-05-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_loyaltitransaction_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedcarSellEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_at', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_variant', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_registration', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
