# Generated by Django 4.1.2 on 2023-06-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_usedcarsellenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcarbooking',
            name='number_of_owners',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usedcarbooking',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usedcarsellenquiry',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
