# Generated by Django 4.1.2 on 2023-06-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_appbooking_gateway_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbooking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
