# Generated by Django 4.1.2 on 2023-06-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_appbooking_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='cust_id_or_reg_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='appbooking',
            name='cust_id_or_reg_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='newcarbooking',
            name='cust_id_or_reg_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cust_id_or_reg_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usedcarbooking',
            name='cust_id_or_reg_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
