# Generated by Django 4.1.2 on 2023-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_accessory_cust_id_or_reg_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbooking',
            name='crmId',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
