# Generated by Django 4.1.2 on 2023-06-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_category_active_status'),
        ('bookings', '0015_appbooking_crmid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbooking',
            name='item_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showcase.itemdescription'),
        ),
    ]
