# Generated by Django 4.1.2 on 2023-06-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_appbooking_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='item_desc_id',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='item_desc_id',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='item_desc_id',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='usedcarbooking',
            old_name='item_desc_id',
            new_name='item_description',
        ),
        migrations.AlterField(
            model_name='appbooking',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Error', 'Error'), ('Declined', 'Declined')], default='Pending', max_length=50),
        ),
    ]
