# Generated by Django 4.2.2 on 2023-06-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_newcarbooking_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalti',
            name='profile',
        ),
        migrations.DeleteModel(
            name='LoyaltiEntity',
        ),
        migrations.RemoveField(
            model_name='loyaltitransaction',
            name='loyalti',
        ),
        migrations.RemoveField(
            model_name='loyaltitransaction',
            name='profile',
        ),
        migrations.AlterField(
            model_name='newcarbooking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Retail', 'Retail'), ('RetailCancel', 'RetailCancel'), ('Deliverred', 'Deliverred')], default='Booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Contacted', 'Contacted'), ('Picked Up', 'Picked Up'), ('Deliverred', 'Deliverred'), ('Cancelled', 'Cancelled')], default='Booked', max_length=50),
        ),
        migrations.DeleteModel(
            name='Loyalti',
        ),
        migrations.DeleteModel(
            name='LoyaltiTransaction',
        ),
    ]
